var namespace_web_analyzer_1_1_events =
[
    [ "AddBrowserEvent", "class_web_analyzer_1_1_events_1_1_add_browser_event.html", "class_web_analyzer_1_1_events_1_1_add_browser_event" ],
    [ "AddConnectionEvent", "class_web_analyzer_1_1_events_1_1_add_connection_event.html", "class_web_analyzer_1_1_events_1_1_add_connection_event" ],
    [ "AddTestrunDataEvent", "class_web_analyzer_1_1_events_1_1_add_testrun_data_event.html", "class_web_analyzer_1_1_events_1_1_add_testrun_data_event" ],
    [ "AddTrackingEvent", "class_web_analyzer_1_1_events_1_1_add_tracking_event.html", "class_web_analyzer_1_1_events_1_1_add_tracking_event" ],
    [ "AddWebpageEvent", "class_web_analyzer_1_1_events_1_1_add_webpage_event.html", "class_web_analyzer_1_1_events_1_1_add_webpage_event" ],
    [ "CreateAOISettingEvent", "class_web_analyzer_1_1_events_1_1_create_a_o_i_setting_event.html", "class_web_analyzer_1_1_events_1_1_create_a_o_i_setting_event" ],
    [ "CreateDomainSettingEvent", "class_web_analyzer_1_1_events_1_1_create_domain_setting_event.html", "class_web_analyzer_1_1_events_1_1_create_domain_setting_event" ],
    [ "CreateExperimentEvent", "class_web_analyzer_1_1_events_1_1_create_experiment_event.html", "class_web_analyzer_1_1_events_1_1_create_experiment_event" ],
    [ "CreateParticipantEvent", "class_web_analyzer_1_1_events_1_1_create_participant_event.html", "class_web_analyzer_1_1_events_1_1_create_participant_event" ],
    [ "CreateRuleEvent", "class_web_analyzer_1_1_events_1_1_create_rule_event.html", "class_web_analyzer_1_1_events_1_1_create_rule_event" ],
    [ "EditApplicationSettingsEvent", "class_web_analyzer_1_1_events_1_1_edit_application_settings_event.html", "class_web_analyzer_1_1_events_1_1_edit_application_settings_event" ],
    [ "EditDomainSettingEvent", "class_web_analyzer_1_1_events_1_1_edit_domain_setting_event.html", "class_web_analyzer_1_1_events_1_1_edit_domain_setting_event" ],
    [ "EditParticipantEvent", "class_web_analyzer_1_1_events_1_1_edit_participant_event.html", "class_web_analyzer_1_1_events_1_1_edit_participant_event" ],
    [ "LoadExperimentEvent", "class_web_analyzer_1_1_events_1_1_load_experiment_event.html", "class_web_analyzer_1_1_events_1_1_load_experiment_event" ],
    [ "MessageSentEvent", "class_web_analyzer_1_1_events_1_1_message_sent_event.html", "class_web_analyzer_1_1_events_1_1_message_sent_event" ],
    [ "PrepareGazeDataEvent", "class_web_analyzer_1_1_events_1_1_prepare_gaze_data_event.html", "class_web_analyzer_1_1_events_1_1_prepare_gaze_data_event" ],
    [ "SaveTestrunEvent", "class_web_analyzer_1_1_events_1_1_save_testrun_event.html", "class_web_analyzer_1_1_events_1_1_save_testrun_event" ],
    [ "SelectExperimentEvent", "class_web_analyzer_1_1_events_1_1_select_experiment_event.html", "class_web_analyzer_1_1_events_1_1_select_experiment_event" ],
    [ "SelectParticipantForTestEvent", "class_web_analyzer_1_1_events_1_1_select_participant_for_test_event.html", "class_web_analyzer_1_1_events_1_1_select_participant_for_test_event" ],
    [ "SelectTestrunToLoadEvent", "class_web_analyzer_1_1_events_1_1_select_testrun_to_load_event.html", "class_web_analyzer_1_1_events_1_1_select_testrun_to_load_event" ],
    [ "TestrunEvent", "class_web_analyzer_1_1_events_1_1_testrun_event.html", "class_web_analyzer_1_1_events_1_1_testrun_event" ],
    [ "TriggerSaveEvent", "class_web_analyzer_1_1_events_1_1_trigger_save_event.html", "class_web_analyzer_1_1_events_1_1_trigger_save_event" ],
    [ "UpdateWSConnectionCountEvent", "class_web_analyzer_1_1_events_1_1_update_w_s_connection_count_event.html", "class_web_analyzer_1_1_events_1_1_update_w_s_connection_count_event" ]
];